LangString welcomeTitle ${LANG_ENGLISH} "Aura Setup"
LangString welcomeText ${LANG_ENGLISH} "Welcome to the Aura Setup Wizard.$\r$\n$\r$\nAura provides fast, accurate voice typing.$\r$\n$\r$\nHold your hotkey (Alt + V) and speak:$\r$\ntranscribed text appears right under your cursor$\r$\nin any active application.$\r$\n$\r$\nClick Next to continue."

LangString finishTitle ${LANG_ENGLISH} "Setup Completed"
LangString finishText ${LANG_ENGLISH} "Aura has been successfully installed.$\r$\n$\r$\nUse the desktop shortcut or Start Menu$\r$\nto launch the app. Default hotkey is Alt + V."

LangString unconfirmTitle ${LANG_ENGLISH} "Uninstall Aura"
LangString unconfirmSubtitle ${LANG_ENGLISH} "Remove Aura from your computer"
LangString unconfirmText ${LANG_ENGLISH} "Aura will be uninstalled from this folder.$\r$\nClick Uninstall to proceed."

LangString addOrReinstall ${LANG_ENGLISH} "Add or Reinstall components"
LangString alreadyInstalled ${LANG_ENGLISH} "Already Installed"
LangString alreadyInstalledLong ${LANG_ENGLISH} "Aura ${VERSION} was found on your system.$\r$\nSelect an operation to continue:"
LangString chooseMaintenanceOption ${LANG_ENGLISH} "Choose an option"
LangString choowHowToInstall ${LANG_ENGLISH} "Choose how to install"
LangString createDesktop ${LANG_ENGLISH} "Create desktop shortcut"
LangString dontUninstall ${LANG_ENGLISH} "Do not uninstall"
LangString dontUninstallDowngrade ${LANG_ENGLISH} "Do not uninstall (downgrade disabled)"
LangString failedToKillApp ${LANG_ENGLISH} "Failed to close Aura. Please close it manually."
LangString installingWebview2 ${LANG_ENGLISH} "Installing Microsoft Edge WebView2..."
LangString newerVersionInstalled ${LANG_ENGLISH} "A newer version of ${PRODUCTNAME} is installed.$\r$\nPlease uninstall it first."
LangString older ${LANG_ENGLISH} "previous"
LangString olderOrUnknownVersionInstalled ${LANG_ENGLISH} "A $R4 version of ${PRODUCTNAME} was detected.$\r$\nSelect an action to continue:"
LangString silentDowngrades ${LANG_ENGLISH} "Silent downgrades are disabled.$\r$\n"
LangString unableToUninstall ${LANG_ENGLISH} "Unable to uninstall previous version."
LangString uninstallApp ${LANG_ENGLISH} "Uninstall Aura from computer"
LangString uninstallBeforeInstalling ${LANG_ENGLISH} "Uninstall previous version before installing"
LangString unknown ${LANG_ENGLISH} "installed"
LangString webview2AbortError ${LANG_ENGLISH} "Failed to install WebView2! The app cannot run without it."
LangString webview2DownloadError ${LANG_ENGLISH} "Error: Downloading WebView2 Failed - $0"
LangString webview2DownloadSuccess ${LANG_ENGLISH} "WebView2 bootstrapper downloaded successfully"
LangString webview2Downloading ${LANG_ENGLISH} "Downloading WebView2 bootstrapper..."
LangString webview2InstallError ${LANG_ENGLISH} "Error: Installing WebView2 failed with exit code $1"
LangString webview2InstallSuccess ${LANG_ENGLISH} "Microsoft Edge WebView2 installed successfully"
LangString deleteAppData ${LANG_ENGLISH} "Delete saved settings and transcription history"
LangString dirPageTitle ${LANG_ENGLISH} "Installation Folder"
LangString dirPageSubtitle ${LANG_ENGLISH} "Select folder to install Aura"
LangString dirPageText ${LANG_ENGLISH} "Aura will be installed into the following folder.$\r$\nTo choose a different folder, click Browse."
LangString appRunning ${LANG_ENGLISH} "Aura is currently running.$\r$\nPlease close it from system tray before continuing."
LangString appRunningOkKill ${LANG_ENGLISH} "Aura is currently running.$\r$\nClick OK to close it automatically."
