LangString welcomeTitle ${LANG_RUSSIAN} "Установка Aura"
LangString welcomeText ${LANG_RUSSIAN} "Вас приветствует мастер Aura.$\r$\n$\r$\nAura — быстрый ввод текста голосом.$\r$\n$\r$\nЗажмите горячую клавишу (Alt + V)$\r$\nи говорите в микрофон: текст появится$\r$\nпрямо в активном окне.$\r$\n$\r$\nНажмите «Далее», чтобы продолжить."

LangString finishTitle ${LANG_RUSSIAN} "Установка завершена"
LangString finishText ${LANG_RUSSIAN} "Aura успешно установлена.$\r$\n$\r$\nДля запуска используйте ярлык на рабочем$\r$\nстоле или в меню «Пуск».$\r$\nПо умолчанию запись — Alt + V."

LangString unconfirmTitle ${LANG_RUSSIAN} "Удаление Aura"
LangString unconfirmSubtitle ${LANG_RUSSIAN} "Удаление программы с вашего компьютера"
LangString unconfirmText ${LANG_RUSSIAN} "Aura будет удалена из следующей папки.$\r$\nНажмите «Удалить», чтобы начать."

LangString addOrReinstall ${LANG_RUSSIAN} "Обновить или переустановить компоненты"
LangString alreadyInstalled ${LANG_RUSSIAN} "Aura уже установлена"
LangString alreadyInstalledLong ${LANG_RUSSIAN} "В системе обнаружена Aura ${VERSION}.$\r$\nВыберите действие для продолжения:"
LangString chooseMaintenanceOption ${LANG_RUSSIAN} "Выберите действие"
LangString choowHowToInstall ${LANG_RUSSIAN} "Выберите способ установки"
LangString createDesktop ${LANG_RUSSIAN} "Создать ярлык на рабочем столе"
LangString dontUninstall ${LANG_RUSSIAN} "Не удалять предыдущую версию"
LangString dontUninstallDowngrade ${LANG_RUSSIAN} "Не удалять (установка старой версии отключена)"
LangString failedToKillApp ${LANG_RUSSIAN} "Не удалось закрыть Aura. Закройте приложение вручную."
LangString installingWebview2 ${LANG_RUSSIAN} "Установка компонента Microsoft Edge WebView2..."
LangString newerVersionInstalled ${LANG_RUSSIAN} "В системе установлена более новая версия ${PRODUCTNAME}.$\r$\nРекомендуется сначала удалить её."
LangString older ${LANG_RUSSIAN} "предыдущая"
LangString olderOrUnknownVersionInstalled ${LANG_RUSSIAN} "В системе обнаружена $R4 версия ${PRODUCTNAME}.$\r$\nВыберите действие для продолжения:"
LangString silentDowngrades ${LANG_RUSSIAN} "Установка старой версии в тихом режиме отключена.$\r$\n"
LangString unableToUninstall ${LANG_RUSSIAN} "Не удалось удалить предыдущую версию."
LangString uninstallApp ${LANG_RUSSIAN} "Удалить Aura с компьютера"
LangString uninstallBeforeInstalling ${LANG_RUSSIAN} "Удалить предыдущую версию перед установкой"
LangString unknown ${LANG_RUSSIAN} "установленная"
LangString webview2AbortError ${LANG_RUSSIAN} "Не удалось установить WebView2. Компонент необходим для работы."
LangString webview2DownloadError ${LANG_RUSSIAN} "Ошибка загрузки WebView2: $0"
LangString webview2DownloadSuccess ${LANG_RUSSIAN} "Компонент WebView2 успешно загружен"
LangString webview2Downloading ${LANG_RUSSIAN} "Загрузка Microsoft Edge WebView2..."
LangString webview2InstallError ${LANG_RUSSIAN} "Ошибка при установке WebView2 (код: $1)"
LangString webview2InstallSuccess ${LANG_RUSSIAN} "Microsoft Edge WebView2 успешно установлен"
LangString deleteAppData ${LANG_RUSSIAN} "Удалить сохранённые настройки и историю записей"
LangString dirPageTitle ${LANG_RUSSIAN} "Папка установки"
LangString dirPageSubtitle ${LANG_RUSSIAN} "Выберите папку для установки Aura"
LangString dirPageText ${LANG_RUSSIAN} "Программа будет установлена в следующую папку.$\r$\nЧтобы выбрать другое расположение, нажмите «Обзор»."
LangString appRunning ${LANG_RUSSIAN} "Aura сейчас запущена.$\r$\nПожалуйста, закройте её в трее перед продолжением."
LangString appRunningOkKill ${LANG_RUSSIAN} "Aura сейчас запущена.$\r$\nНажмите ОК, чтобы закрыть её автоматически."
